/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Yelson
 */
public class ClientRegister extends javax.swing.JFrame {

    /**
     * Creates new form windowRegister
     */
    public ClientRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon image = new ImageIcon("src/images/icon.png");
        this.setIconImage(image.getImage());
        
        //Para que no sea permitido brincarse los pasos
        this.jTabbedPane.setSelectedIndex(0);
        this.jTabbedPane.setEnabledAt(1, false);
        this.jTabbedPane.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelUser = new javax.swing.JPanel();
        txtLastName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnContinue1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox<>();
        txtState1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanelService = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        btnContinue2 = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jPanelPay = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnContinue3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnQuestions = new javax.swing.JButton();
        label_background = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jLabel27.setText("jLabel27");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(17, 31, 77));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelUser.setBackground(new java.awt.Color(245, 245, 245));
        jPanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanelUser.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 170, 30));

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanelUser.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, 30));
        txtName.getAccessibleContext().setAccessibleName("");

        jPanelUser.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, 30));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        jPanelUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(110, 190, 68));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DATOS PERSONALES");
        jPanelUser.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jPanelUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha de Nacimiento:");
        jPanelUser.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        btnContinue1.setBackground(new java.awt.Color(110, 190, 68));
        btnContinue1.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnContinue1.setForeground(new java.awt.Color(242, 244, 247));
        btnContinue1.setText("CONTINUAR");
        btnContinue1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUser.add(btnContinue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 40));

        jLabel19.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("País:");
        jPanelUser.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, 30));
        jPanelUser.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 170, 30));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Estado:");
        jPanelUser.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 30));

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelUser.add(cmbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, 30));
        jPanelUser.add(txtState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 450, 30));

        jLabel21.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Ubicación:");
        jPanelUser.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jTabbedPane.addTab("Paso 1 ", jPanelUser);

        jPanelService.setBackground(new java.awt.Color(245, 245, 245));
        jPanelService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(110, 190, 68));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("DATOS DE LA CUENTA");
        jPanelService.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnBack2.setBackground(new java.awt.Color(204, 204, 204));
        btnBack2.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(51, 51, 51));
        btnBack2.setText("REGRESAR");
        btnBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelService.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 40));

        btnContinue2.setBackground(new java.awt.Color(110, 190, 68));
        btnContinue2.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnContinue2.setForeground(new java.awt.Color(242, 244, 247));
        btnContinue2.setText("CONTINUAR");
        btnContinue2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelService.add(btnContinue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 180, 40));
        jPanelService.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 180, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número Telefónico:");
        jPanelService.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contraseña:");
        jPanelService.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 30));
        jPanelService.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, 30));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Confirmar:");
        jPanelService.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 30));
        jPanelService.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 150, 30));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Correo Electrónico:");
        jPanelService.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));
        jPanelService.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 380, 30));

        jTabbedPane.addTab("Paso 2 ", jPanelService);

        jPanelPay.setBackground(new java.awt.Color(242, 244, 247));
        jPanelPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(110, 190, 68));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("DATOS DE PAGO");
        jPanelPay.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnBack3.setBackground(new java.awt.Color(204, 204, 204));
        btnBack3.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(51, 51, 51));
        btnBack3.setText("REGRESAR");
        btnBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPay.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, 40));

        btnContinue3.setBackground(new java.awt.Color(110, 190, 68));
        btnContinue3.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnContinue3.setForeground(new java.awt.Color(242, 244, 247));
        btnContinue3.setText("CONTINUAR");
        btnContinue3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPay.add(btnContinue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 180, 40));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Fecha de Vencimiento:");
        jPanelPay.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        txtCardNumber.setToolTipText("");
        txtCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumberActionPerformed(evt);
            }
        });
        jPanelPay.add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 380, 30));
        jPanelPay.add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 30));
        jPanelPay.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 60, 30));

        jLabel17.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Número de Tarjeta:");
        jPanelPay.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 30));

        jLabel18.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("CVV:");
        jPanelPay.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 40, 30));

        txtCVV.setToolTipText("");
        txtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVVActionPerformed(evt);
            }
        });
        jPanelPay.add(txtCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, 30));

        jTabbedPane.addTab("Paso 3 ", jPanelPay);

        jPanel1.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 620, 350));

        btnBack.setBackground(new java.awt.Color(17, 31, 77));
        btnBack.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 40, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 190, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 450, 30));

        btnQuestions.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnQuestions.setForeground(new java.awt.Color(17, 31, 77));
        btnQuestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        btnQuestions.setBorder(null);
        btnQuestions.setBorderPainted(false);
        btnQuestions.setContentAreaFilled(false);
        btnQuestions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionsActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 40, -1));

        label_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_client.png"))); // NOI18N
        jPanel1.add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void btnQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuestionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnBack2;
    public javax.swing.JButton btnBack3;
    public javax.swing.JButton btnContinue1;
    public javax.swing.JButton btnContinue2;
    public javax.swing.JButton btnContinue3;
    public javax.swing.JButton btnQuestions;
    private javax.swing.JComboBox<String> cmbCountry;
    private javax.swing.JButton jButton2;
    public com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelService;
    private javax.swing.JPanel jPanelUser;
    public javax.swing.JTabbedPane jTabbedPane;
    public com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel label_background;
    public javax.swing.JTextField txtCVV;
    public javax.swing.JTextField txtCardNumber;
    public javax.swing.JPasswordField txtConfirmPassword;
    public javax.swing.JTextField txtEmail1;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtPhoneNumber;
    public javax.swing.JTextField txtState;
    public javax.swing.JTextField txtState1;
    // End of variables declaration//GEN-END:variables
}
