/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UIController;
import javax.swing.ImageIcon;

/**
 *
 * @author Yelson
 */
public class ManagerStatistics extends javax.swing.JFrame {

    private UIController uiController;
    
    public ManagerStatistics(UIController pUiController) {
        uiController=pUiController;
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon image = new ImageIcon("src/images/icon.png");
        this.setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventory = new javax.swing.JButton();
        btnOffers = new javax.swing.JButton();
        lblInstructionsTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnInventory1 = new javax.swing.JButton();
        btnOffers1 = new javax.swing.JButton();
        lblInstructionsTitle1 = new javax.swing.JLabel();
        label_background = new javax.swing.JLabel();
        btnInventory2 = new javax.swing.JButton();

        btnInventory.setBackground(new java.awt.Color(151, 151, 151));
        btnInventory.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventario");
        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventoryMouseEntered(evt);
            }
        });

        btnOffers.setBackground(new java.awt.Color(151, 151, 151));
        btnOffers.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        btnOffers.setForeground(new java.awt.Color(255, 255, 255));
        btnOffers.setText("Promociones");
        btnOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOffers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOffersMouseEntered(evt);
            }
        });

        lblInstructionsTitle.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblInstructionsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblInstructionsTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInstructionsTitle.setText("Administración de Productos");
        lblInstructionsTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(53, 57, 65));
        btnMenu.setText("Inicio");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        btnProduct.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(53, 57, 65));
        btnProduct.setText("Productos");
        btnProduct.setBorder(null);
        btnProduct.setBorderPainted(false);
        btnProduct.setContentAreaFilled(false);
        btnProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, -1));

        btnEmployee.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(53, 57, 65));
        btnEmployee.setText("Empleados");
        btnEmployee.setBorder(null);
        btnEmployee.setBorderPainted(false);
        btnEmployee.setContentAreaFilled(false);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 80, -1));

        btnStats.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnStats.setForeground(new java.awt.Color(110, 190, 68));
        btnStats.setText("Estadísticas");
        btnStats.setBorder(null);
        btnStats.setBorderPainted(false);
        btnStats.setContentAreaFilled(false);
        btnStats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btnStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 57, 65));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("|");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 20, 20));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 57, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("|");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 20, 20));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 57, 65));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("|");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 20, 20));

        btnExit.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(113, 117, 125));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar Sesión");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 40, -1));

        btnInventory1.setBackground(new java.awt.Color(151, 151, 151));
        btnInventory1.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        btnInventory1.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory1.setText("Ventas");
        btnInventory1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventory1MouseEntered(evt);
            }
        });
        btnInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventory1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 40));

        btnOffers1.setBackground(new java.awt.Color(151, 151, 151));
        btnOffers1.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        btnOffers1.setForeground(new java.awt.Color(255, 255, 255));
        btnOffers1.setText("Ganancias");
        btnOffers1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOffers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOffers1MouseEntered(evt);
            }
        });
        btnOffers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffers1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOffers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 240, 40));

        lblInstructionsTitle1.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblInstructionsTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblInstructionsTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInstructionsTitle1.setText("Estadísticas de la empresa");
        lblInstructionsTitle1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblInstructionsTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 250, 30));

        label_background.setForeground(new java.awt.Color(53, 57, 65));
        label_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_manager_2.png"))); // NOI18N
        jPanel1.add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        btnInventory2.setBackground(new java.awt.Color(151, 151, 151));
        btnInventory2.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        btnInventory2.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory2.setText("Inventario");
        btnInventory2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInventory2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventory2MouseEntered(evt);
            }
        });
        jPanel1.add(btnInventory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseEntered
        // TODO add your handling code here:
        this.lblInstructionsTitle.setText("Administración del Inventario");
        String text = "<html><p>Permite tener un control total de los productos"
        + " alamcenados en las establecimientos, además de de los muebles"
        + " producidos en cada taller.</p></html>";
        //this.lblInstructions.setText(text);
    }//GEN-LAST:event_btnInventoryMouseEntered

    private void btnOffersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffersMouseEntered
        // TODO add your handling code here:
        this.lblInstructionsTitle.setText("Administración de Promociones");
        String text = "<html><p>Permite la gestión de las ofertas y promociones"
        + "que estarán disponibles paras los clientes de todas las sedes"
        + "de la empresa</p></html>";
        //this.lblInstructions.setText(text);
    }//GEN-LAST:event_btnOffersMouseEntered

    private void btnInventory1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventory1MouseEntered
        // TODO add your handling code here:
        this.lblInstructionsTitle.setText("Administración del Inventario");
        String text = "<html><p>Permite tener un control total de los productos"
        + " alamcenados en las establecimientos, además de de los muebles"
        + " producidos en cada taller.</p></html>";
        //this.lblInstructions.setText(text);
    }//GEN-LAST:event_btnInventory1MouseEntered

    private void btnOffers1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffers1MouseEntered
        // TODO add your handling code here:
        this.lblInstructionsTitle.setText("Administración de Promociones");
        String text = "<html><p>Permite la gestión de las ofertas y promociones"
        + "que estarán disponibles paras los clientes de todas las sedes"
        + "de la empresa</p></html>";
        //this.lblInstructions.setText(text);
    }//GEN-LAST:event_btnOffers1MouseEntered

    private void btnInventory2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventory2MouseEntered
        // TODO add your handling code here:
        uiController.showWindow(ManagerStatisticsProfit.class);
        this.setVisible(false);
    }//GEN-LAST:event_btnInventory2MouseEntered

    private void btnInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventory1ActionPerformed
        // TODO add your handling code here:
        uiController.showWindow(ManagerStatisticsSales.class);
        this.setVisible(false);
    }//GEN-LAST:event_btnInventory1ActionPerformed

    private void btnOffers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffers1ActionPerformed
        // TODO add your handling code here:
        uiController.showWindow(ManagerStatisticsProfit.class);
        this.setVisible(false);
    }//GEN-LAST:event_btnOffers1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        uiController.showWindow(ManagerMenu.class);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerStatistics(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnInventory;
    public javax.swing.JButton btnInventory1;
    public javax.swing.JButton btnInventory2;
    private javax.swing.JButton btnMenu;
    public javax.swing.JButton btnOffers;
    public javax.swing.JButton btnOffers1;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnStats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel lblInstructionsTitle;
    private javax.swing.JLabel lblInstructionsTitle1;
    // End of variables declaration//GEN-END:variables
}
